name: state_management
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  dio: ^4.0.3
  retrofit: ^3.0.0
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  intl: ^0.17.0
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  retrofit_generator: any
  build_runner: any

flutter:
  uses-material-design: true
